In [5]:
import os
os.environ["PYSPARK_PYTHON"]='PYTHON'

In [6]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("BusData").getOrCreate()

In [7]:
# The Raw files in the folder are read
raw_path = "Data/Raw"
files = os.listdir(raw_path)
print(files)

['.ipynb_checkpoints', 'agency.txt', 'calendar.txt', 'calendar_dates.txt', 'distrubtion.csv', 'feed_info.txt', 'routes.txt', 'shapes.txt', 'siri.xml', 'sirisx.xml', 'stops.txt', 'stop_times.txt', 'trips.txt', 'vehicle.csv']

# Read every GTFS txt file from the raw Data

In [8]:
gtfs = {}
for file in files:
    if file.endswith(".txt"):
        name = file.replace(".txt","")
        df = spark.read.csv(os.path.join(raw_path,file),header=True,inferSchema=True)
        gtfs[name] = df
print(gtfs.keys())

dict_keys(['agency', 'calendar', 'calendar_dates', 'feed_info', 'routes', 'shapes', 'stops', 'stop_times', 'trips'])

# Exploring the Data

In [9]:
# Explore each dataset with rows , column and Schema
for name, df in gtfs.items():
    print(name.upper())
    print("-"*70)
    print("Rows :", df.count())
    print("Columns :", len(df.columns))
    df.printSchema()
    df.show(5, truncate=False)

AGENCY
----------------------------------------------------------------------
Rows : 70
Columns : 7
root
 |-- agency_id: string (nullable = true)
 |-- agency_name: string (nullable = true)
 |-- agency_url: string (nullable = true)
 |-- agency_timezone: string (nullable = true)
 |-- agency_lang: string (nullable = true)
 |-- agency_phone: string (nullable = true)
 |-- agency_noc: string (nullable = true)

+---------+--------------+--------------------------+---------------+-----------+------------+----------+
|agency_id|agency_name   |agency_url                |agency_timezone|agency_lang|agency_phone|agency_noc|
+---------+--------------+--------------------------+---------------+-----------+------------+----------+
|OP10     |M & H Coaches |https://www.traveline.info|Europe/London  |EN         |NULL        |MHCO      |
|OP1092   |Mersey Ferries|https://www.traveline.info|Europe/London  |EN         |NULL        |FRRY      |
|OP10924  |Bee Network   |https://www.traveline.info|Europe/London  |EN         |NULL        |BNSM      |
|OP11023  |Bee Network   |https://www.traveline.info|Europe/London  |EN         |NULL        |BNDB      |
|OP11056  |Bee Network   |https://www.traveline.info|Europe/London  |EN         |NULL        |BNVB      |
+---------+--------------+--------------------------+---------------+-----------+------------+----------+
only showing top 5 rows

CALENDAR
----------------------------------------------------------------------
Rows : 277
Columns : 10
root
 |-- service_id: integer (nullable = true)
 |-- monday: integer (nullable = true)
 |-- tuesday: integer (nullable = true)
 |-- wednesday: integer (nullable = true)
 |-- thursday: integer (nullable = true)
 |-- friday: integer (nullable = true)
 |-- saturday: integer (nullable = true)
 |-- sunday: integer (nullable = true)
 |-- start_date: integer (nullable = true)
 |-- end_date: integer (nullable = true)

+----------+------+-------+---------+--------+------+--------+------+----------+--------+
|service_id|monday|tuesday|wednesday|thursday|friday|saturday|sunday|start_date|end_date|
+----------+------+-------+---------+--------+------+--------+------+----------+--------+
|1         |1     |1      |1        |1       |1     |1       |0     |20260702  |20270402|
|3         |0     |0      |0        |0       |0     |1       |0     |20260702  |20270402|
|4         |1     |1      |1        |1       |1     |0       |0     |20260702  |20270402|
|15        |0     |0      |0        |0       |0     |1       |0     |20260702  |20261024|
|16        |1     |1      |1        |1       |1     |0       |0     |20260702  |20261024|
+----------+------+-------+---------+--------+------+--------+------+----------+--------+
only showing top 5 rows

CALENDAR_DATES
----------------------------------------------------------------------
Rows : 24097
Columns : 3
root
 |-- service_id: integer (nullable = true)
 |-- date: integer (nullable = true)
 |-- exception_type: integer (nullable = true)

+----------+--------+--------------+
|service_id|date    |exception_type|
+----------+--------+--------------+
|31967     |20260918|1             |
|29016     |20261207|2             |
|17590     |20260802|1             |
|17589     |20260719|1             |
|29491     |20261204|2             |
+----------+--------+--------------+
only showing top 5 rows

FEED_INFO
----------------------------------------------------------------------
Rows : 1
Columns : 6
root
 |-- feed_publisher_name: string (nullable = true)
 |-- feed_publisher_url: string (nullable = true)
 |-- feed_lang: string (nullable = true)
 |-- feed_start_date: integer (nullable = true)
 |-- feed_end_date: integer (nullable = true)
 |-- feed_version: string (nullable = true)

+----------------------------+--------------------------------+---------+---------------+-------------+---------------+
|feed_publisher_name         |feed_publisher_url              |feed_lang|feed_start_date|feed_end_date|feed_version   |
+----------------------------+--------------------------------+---------+---------------+-------------+---------------+
|Bus Open Data Service (BODS)|https://www.bus-data.dft.gov.uk/|EN       |20260702       |21250928     |20260702_024645|
+----------------------------+--------------------------------+---------+---------------+-------------+---------------+

ROUTES
----------------------------------------------------------------------
Rows : 1669
Columns : 5
root
 |-- route_id: integer (nullable = true)
 |-- agency_id: string (nullable = true)
 |-- route_short_name: string (nullable = true)
 |-- route_long_name: string (nullable = true)
 |-- route_type: integer (nullable = true)

+--------+---------+----------------+---------------+----------+
|route_id|agency_id|route_short_name|route_long_name|route_type|
+--------+---------+----------------+---------------+----------+
|8       |OP6      |4               |NULL           |3         |
|30      |OP6      |4S              |NULL           |3         |
|46      |OP6      |14              |NULL           |3         |
|77      |OP6      |10              |NULL           |3         |
|92      |OP6      |11              |NULL           |3         |
+--------+---------+----------------+---------------+----------+
only showing top 5 rows

SHAPES
----------------------------------------------------------------------
Rows : 2921218
Columns : 5
root
 |-- shape_id: string (nullable = true)
 |-- shape_pt_lat: double (nullable = true)
 |-- shape_pt_lon: double (nullable = true)
 |-- shape_pt_sequence: integer (nullable = true)
 |-- shape_dist_traveled: string (nullable = true)

+------------------------------------+------------+------------+-----------------+-------------------+
|shape_id                            |shape_pt_lat|shape_pt_lon|shape_pt_sequence|shape_dist_traveled|
+------------------------------------+------------+------------+-----------------+-------------------+
|0016ec85-f116-4244-b447-7965b1077676|54.04671    |-2.79849    |52               |NULL               |
|0016ec85-f116-4244-b447-7965b1077676|54.04671    |-2.79839    |51               |NULL               |
|0016ec85-f116-4244-b447-7965b1077676|54.04671    |-2.79835    |50               |NULL               |
|0016ec85-f116-4244-b447-7965b1077676|54.04672    |-2.79891    |54               |NULL               |
|0016ec85-f116-4244-b447-7965b1077676|54.04672    |-2.79874    |53               |NULL               |
+------------------------------------+------------+------------+-----------------+-------------------+
only showing top 5 rows

STOPS
----------------------------------------------------------------------
Rows : 36607
Columns : 9
root
 |-- stop_id: string (nullable = true)
 |-- stop_code: string (nullable = true)
 |-- stop_name: string (nullable = true)
 |-- stop_lat: double (nullable = true)
 |-- stop_lon: double (nullable = true)
 |-- wheelchair_boarding: integer (nullable = true)
 |-- location_type: integer (nullable = true)
 |-- parent_station: string (nullable = true)
 |-- platform_code: string (nullable = true)

+------------+---------+-------------+----------------+-------------------+-------------------+-------------+--------------+-------------+
|stop_id     |stop_code|stop_name    |stop_lat        |stop_lon           |wheelchair_boarding|location_type|parent_station|platform_code|
+------------+---------+-------------+----------------+-------------------+-------------------+-------------+--------------+-------------+
|2500DCL792  |landmwdg |New Line     |53.690549138    |-2.182164321       |0                  |0            |NULL          |NULL         |
|090033104077|cumdpjmt |Ness Way     |54.8846026352862|-2.9681880886133096|0                  |0            |NULL          |NULL         |
|0600MA19191 |cheagjap |Smith Lane   |53.331856       |-2.339258          |0                  |0            |NULL          |NULL         |
|2800S44079B |merdmpjg |Eaton Road   |53.42999        |-2.90919           |0                  |0            |NULL          |NULL         |
|2500IMG2876 |langjdpa |Rosehill Road|53.782133294    |-2.253630925       |0                  |0            |NULL          |NULL         |
+------------+---------+-------------+----------------+-------------------+-------------------+-------------+--------------+-------------+
only showing top 5 rows

STOP_TIMES
----------------------------------------------------------------------
Rows : 5195977
Columns : 10
root
 |-- trip_id: string (nullable = true)
 |-- arrival_time: string (nullable = true)
 |-- departure_time: string (nullable = true)
 |-- stop_id: string (nullable = true)
 |-- stop_sequence: integer (nullable = true)
 |-- stop_headsign: string (nullable = true)
 |-- pickup_type: integer (nullable = true)
 |-- drop_off_type: integer (nullable = true)
 |-- shape_dist_traveled: string (nullable = true)
 |-- timepoint: integer (nullable = true)

+------------------------------------------+------------+--------------+------------+-------------+-------------+-----------+-------------+-------------------+---------+
|trip_id                                   |arrival_time|departure_time|stop_id     |stop_sequence|stop_headsign|pickup_type|drop_off_type|shape_dist_traveled|timepoint|
+------------------------------------------+------------+--------------+------------+-------------+-------------+-----------+-------------+-------------------+---------+
|VJ00022cf38fdf14a7a8ab5d98cc7e02aac0a8e154|06:59:00    |06:59:00      |9400ZZMAFIR2|0            |NULL         |0          |1            |NULL               |1        |
|VJ00022cf38fdf14a7a8ab5d98cc7e02aac0a8e154|07:01:00    |07:01:00      |9400ZZMACHO2|1            |NULL         |0          |0            |NULL               |1        |
|VJ00022cf38fdf14a7a8ab5d98cc7e02aac0a8e154|07:02:00    |07:02:00      |9400ZZMASTW2|2            |NULL         |0          |0            |NULL               |1        |
|VJ00022cf38fdf14a7a8ab5d98cc7e02aac0a8e154|07:05:00    |07:05:00      |9400ZZMAWIT2|3            |NULL         |0          |0            |NULL               |1        |
|VJ00022cf38fdf14a7a8ab5d98cc7e02aac0a8e154|07:07:00    |07:07:00      |9400ZZMABNR2|4            |NULL         |0          |0            |NULL               |1        |
+------------------------------------------+------------+--------------+------------+-------------+-------------+-----------+-------------+-------------------+---------+
only showing top 5 rows

TRIPS
----------------------------------------------------------------------
Rows : 120474
Columns : 9
root
 |-- route_id: integer (nullable = true)
 |-- service_id: integer (nullable = true)
 |-- trip_id: string (nullable = true)
 |-- trip_headsign: string (nullable = true)
 |-- direction_id: integer (nullable = true)
 |-- block_id: string (nullable = true)
 |-- shape_id: string (nullable = true)
 |-- wheelchair_accessible: integer (nullable = true)
 |-- vehicle_journey_code: string (nullable = true)

+--------+----------+------------------------------------------+---------------+------------+--------+--------+---------------------+--------------------+
|route_id|service_id|trip_id                                   |trip_headsign  |direction_id|block_id|shape_id|wheelchair_accessible|vehicle_journey_code|
+--------+----------+------------------------------------------+---------------+------------+--------+--------+---------------------+--------------------+
|8       |60        |VJ008f72c7264e51cf346fb24257a9f2e9fd702262|Railway Station|1           |NULL    |NULL    |0                    |vj_1                |
|8       |60        |VJ00b3f1406d79a81b4f8c04326cff82f90bbb27eb|Railway Station|1           |NULL    |NULL    |0                    |vj_11               |
|8       |60        |VJ04981b88d9836bcacf96a432f75d9bf1f30c0c41|Bus Station    |0           |NULL    |NULL    |0                    |vj_22               |
|8       |97        |VJ091fbab84e764ccad5143c5acb57132742979626|Bus Station    |0           |NULL    |NULL    |0                    |vj_16               |
|8       |60        |VJ1017064c449c957e133f732a0533f5cf3b9adb55|Railway Station|1           |NULL    |NULL    |0                    |vj_8                |
+--------+----------+------------------------------------------+---------------+------------+--------+--------+---------------------+--------------------+
only showing top 5 rows

In [10]:
# Statistical Summary
for name, df in gtfs.items():
    print(f"\n{name}")
    df.describe().show()

agency
+-------+---------+--------------------+--------------------+---------------+-----------+-------------+----------+
|summary|agency_id|         agency_name|          agency_url|agency_timezone|agency_lang| agency_phone|agency_noc|
+-------+---------+--------------------+--------------------+---------------+-----------+-------------+----------+
|  count|       70|                  70|                  70|             70|         70|            2|        70|
|   mean|     NULL|                NULL|                NULL|           NULL|       NULL|         NULL|      NULL|
| stddev|     NULL|                NULL|                NULL|           NULL|       NULL|         NULL|      NULL|
|    min|     OP10|       A and J Taxis|https://www.trave...|  Europe/London|         EN| 01576 203874|      A2BC|
|    max|    OP853|Wright Brothers C...|https://www.trave...|  Europe/London|         EN|0161 205 2000|      WGTB|
+-------+---------+--------------------+--------------------+---------------+-----------+-------------+----------+


calendar
+-------+-----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+--------------------+------------------+
|summary|       service_id|            monday|           tuesday|         wednesday|          thursday|            friday|           saturday|             sunday|          start_date|          end_date|
+-------+-----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+--------------------+------------------+
|  count|              277|               277|               277|               277|               277|               277|                277|                277|                 277|               277|
|   mean|17193.92057761733| 0.516245487364621|0.4981949458483754| 0.516245487364621|0.5631768953068592|0.5848375451263538|0.33935018050541516|  0.296028880866426|2.0264285462093864E7|2.02695043032491E7|
| stddev|12874.17303778043|0.5006405147656872|0.5009017139876966|0.5006405147656872|0.4968903457465469| 0.493641884840938| 0.4743457852988307|0.45733012118444977|   59482.84485264547| 59367.30465025937|
|    min|                1|                 0|                 0|                 0|                 0|                 0|                  0|                  0|            20260702|          20260704|
|    max|            37359|                 1|                 1|                 1|                 1|                 1|                  1|                  1|            21250703|          21250928|
+-------+-----------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+--------------------+------------------+


calendar_dates
+-------+------------------+--------------------+------------------+
|summary|        service_id|                date|    exception_type|
+-------+------------------+--------------------+------------------+
|  count|             24097|               24097|             24097|
|   mean|24706.683612067893|2.0263182672365855E7|1.4149894177698468|
| stddev|10530.134453595601|  3931.3652525996827|0.4927304295027184|
|    min|                15|            20260702|                 1|
|    max|             46244|            20270503|                 2|
+-------+------------------+--------------------+------------------+


feed_info
+-------+--------------------+--------------------+---------+---------------+-------------+---------------+
|summary| feed_publisher_name|  feed_publisher_url|feed_lang|feed_start_date|feed_end_date|   feed_version|
+-------+--------------------+--------------------+---------+---------------+-------------+---------------+
|  count|                   1|                   1|        1|              1|            1|              1|
|   mean|                NULL|                NULL|     NULL|    2.0260702E7|  2.1250928E7|           NULL|
| stddev|                NULL|                NULL|     NULL|           NULL|         NULL|           NULL|
|    min|Bus Open Data Ser...|https://www.bus-d...|       EN|       20260702|     21250928|20260702_024645|
|    max|Bus Open Data Ser...|https://www.bus-d...|       EN|       20260702|     21250928|20260702_024645|
+-------+--------------------+--------------------+---------+---------------+-------------+---------------+


routes
+-------+------------------+---------+------------------+---------------+-----------------+
|summary|          route_id|agency_id|  route_short_name|route_long_name|       route_type|
+-------+------------------+---------+------------------+---------------+-----------------+
|  count|              1669|     1669|              1669|              0|             1669|
|   mean|  839159.409227082|     NULL|445.43491577335374|           NULL|7.565008987417615|
| stddev|2242823.9827106455|     NULL|335.20198859110826|           NULL|29.77705122558589|
|    min|                 8|     OP10|                 1|           NULL|                0|
|    max|          11677305|    OP853|                x2|           NULL|              200|
+-------+------------------+---------+------------------+---------------+-----------------+


shapes
+-------+--------------------+------------------+-------------------+-----------------+-------------------+
|summary|            shape_id|      shape_pt_lat|       shape_pt_lon|shape_pt_sequence|shape_dist_traveled|
+-------+--------------------+------------------+-------------------+-----------------+-------------------+
|  count|             2921218|           2921218|            2921218|          2921218|                  0|
|   mean|                NULL| 53.90577998384262|-2.8329154011364586|749.8663033707173|               NULL|
| stddev|                NULL|0.5106614849783084|0.29845768952916324|648.1294829030476|               NULL|
|    min|0016ec85-f116-424...|         53.022272|           -3.60719|                0|               NULL|
|    max|ffe90f7e-b84d-45f...|          55.95693|          -1.857762|             5367|               NULL|
+-------+--------------------+------------------+-------------------+-----------------+-------------------+


stops
+-------+--------------------+--------------------+---------------+-------------------+-------------------+-------------------+-------------------+--------------+------------------+
|summary|             stop_id|           stop_code|      stop_name|           stop_lat|           stop_lon|wheelchair_boarding|      location_type|parent_station|     platform_code|
+-------+--------------------+--------------------+---------------+-------------------+-------------------+-------------------+-------------------+--------------+------------------+
|  count|               36607|               34674|          36607|              36607|              36607|              36607|              36607|           699|               523|
|   mean|6.699701222403819E10| 4.523467327341227E7|           NULL| 53.625532932623216|  -2.58456276857148|                0.0|0.00557270467396946|          NULL|7.8040816326530615|
| stddev|9.046988537534349E10|1.3583611989655426E7|           NULL|0.41504860531354615|0.37129476796593947|                0.0|0.07517361722741078|          NULL|  9.25339900296442|
|    min|        000000000ZGB|            32000983|10 Langley Road|           51.06156| -4.251722199402544|                  0|                  0|      010G0005|                 0|
|    max|         940GZZMAWYT|            wsxamjga|        village|          55.955515|           0.936863|                  0|                  2|   940GZZMAWYT|                 Y|
+-------+--------------------+--------------------+---------------+-------------------+-------------------+-------------------+-------------------+--------------+------------------+


stop_times
+-------+--------------------+------------+--------------+--------------------+------------------+-------------+-------------------+--------------------+-------------------+-------------------+
|summary|             trip_id|arrival_time|departure_time|             stop_id|     stop_sequence|stop_headsign|        pickup_type|       drop_off_type|shape_dist_traveled|          timepoint|
+-------+--------------------+------------+--------------+--------------------+------------------+-------------+-------------------+--------------------+-------------------+-------------------+
|  count|             5195977|     5195977|       5195977|             5195977|           5195977|            0|            5195977|             5195977|                  0|            5195977|
|   mean|                NULL|        NULL|          NULL| 5.19301362438173E10|26.346623936172158|         NULL|0.02328166579644213|0.024357113205081545|               NULL|0.16968589352878197|
| stddev|                NULL|        NULL|          NULL|5.219139317872677...|20.093496303821812|         NULL| 0.1507966651175593| 0.15415527501485432|               NULL| 0.3753566546390687|
|    min|VJ00022cf38fdf14a...|    00:00:00|      00:00:00|        000000000ZGB|                 0|         NULL|                  0|                   0|               NULL|                  0|
|    max|VJffffea164b8a5e0...|    33:25:00|      33:25:00|        9400ZZMAWYT2|               128|         NULL|                  1|                   1|               NULL|                  1|
+-------+--------------------+------------+--------------+--------------------+------------------+-------------+-------------------+--------------------+-------------------+-------------------+


trips
+-------+------------------+------------------+--------------------+------------------+------------------+--------------------+--------------------+---------------------+--------------------+
|summary|          route_id|        service_id|             trip_id|     trip_headsign|      direction_id|            block_id|            shape_id|wheelchair_accessible|vehicle_journey_code|
+-------+------------------+------------------+--------------------+------------------+------------------+--------------------+--------------------+---------------------+--------------------+
|  count|            120474|            120474|              120474|            120423|            120474|               39319|               47821|               120474|              120474|
|   mean| 900575.0743894948| 6531.845120108903|                NULL|          204.3125|0.4468350017431147|                NULL|                NULL|                  0.0|   40835.17674174961|
| stddev|2408649.8246964407|11292.802167743386|                NULL|3.8939054944874996|0.4971675116621013|                NULL|                NULL|                  0.0|   510108.4416654359|
|    min|                 8|                 1|VJ00022cf38fdf14a...|               198|                 0|0005583d0efb44454...|0016ec85-f116-424...|                    0|                   1|
|    max|          11677305|             46244|VJffffea164b8a5e0...|      Zoo Entrance|                 1|fff88c318d7ed74db...|ffe90f7e-b84d-45f...|                    0|               vj_99|
+-------+------------------+------------------+--------------------+------------------+------------------+--------------------+--------------------+---------------------+--------------------+

In [11]:
# Missing Values
from pyspark.sql.functions import col,isnan,when,count

for name,df in gtfs.items():

    print(f"\n{name}")

    df.select([
        count(when(col(c).isNull(),c)).alias(c)
        for c in df.columns
    ]).show()

agency
+---------+-----------+----------+---------------+-----------+------------+----------+
|agency_id|agency_name|agency_url|agency_timezone|agency_lang|agency_phone|agency_noc|
+---------+-----------+----------+---------------+-----------+------------+----------+
|        0|          0|         0|              0|          0|          68|         0|
+---------+-----------+----------+---------------+-----------+------------+----------+


calendar
+----------+------+-------+---------+--------+------+--------+------+----------+--------+
|service_id|monday|tuesday|wednesday|thursday|friday|saturday|sunday|start_date|end_date|
+----------+------+-------+---------+--------+------+--------+------+----------+--------+
|         0|     0|      0|        0|       0|     0|       0|     0|         0|       0|
+----------+------+-------+---------+--------+------+--------+------+----------+--------+


calendar_dates
+----------+----+--------------+
|service_id|date|exception_type|
+----------+----+--------------+
|         0|   0|             0|
+----------+----+--------------+


feed_info
+-------------------+------------------+---------+---------------+-------------+------------+
|feed_publisher_name|feed_publisher_url|feed_lang|feed_start_date|feed_end_date|feed_version|
+-------------------+------------------+---------+---------------+-------------+------------+
|                  0|                 0|        0|              0|            0|           0|
+-------------------+------------------+---------+---------------+-------------+------------+


routes
+--------+---------+----------------+---------------+----------+
|route_id|agency_id|route_short_name|route_long_name|route_type|
+--------+---------+----------------+---------------+----------+
|       0|        0|               0|           1669|         0|
+--------+---------+----------------+---------------+----------+


shapes
+--------+------------+------------+-----------------+-------------------+
|shape_id|shape_pt_lat|shape_pt_lon|shape_pt_sequence|shape_dist_traveled|
+--------+------------+------------+-----------------+-------------------+
|       0|           0|           0|                0|            2921218|
+--------+------------+------------+-----------------+-------------------+


stops
+-------+---------+---------+--------+--------+-------------------+-------------+--------------+-------------+
|stop_id|stop_code|stop_name|stop_lat|stop_lon|wheelchair_boarding|location_type|parent_station|platform_code|
+-------+---------+---------+--------+--------+-------------------+-------------+--------------+-------------+
|      0|     1933|        0|       0|       0|                  0|            0|         35908|        36084|
+-------+---------+---------+--------+--------+-------------------+-------------+--------------+-------------+


stop_times
+-------+------------+--------------+-------+-------------+-------------+-----------+-------------+-------------------+---------+
|trip_id|arrival_time|departure_time|stop_id|stop_sequence|stop_headsign|pickup_type|drop_off_type|shape_dist_traveled|timepoint|
+-------+------------+--------------+-------+-------------+-------------+-----------+-------------+-------------------+---------+
|      0|           0|             0|      0|            0|      5195977|          0|            0|            5195977|        0|
+-------+------------+--------------+-------+-------------+-------------+-----------+-------------+-------------------+---------+


trips
+--------+----------+-------+-------------+------------+--------+--------+---------------------+--------------------+
|route_id|service_id|trip_id|trip_headsign|direction_id|block_id|shape_id|wheelchair_accessible|vehicle_journey_code|
+--------+----------+-------+-------------+------------+--------+--------+---------------------+--------------------+
|       0|         0|      0|           51|           0|   81155|   72653|                    0|                   0|
+--------+----------+-------+-------------+------------+--------+--------+---------------------+--------------------+

In [12]:
# Dublicate Values
for name,df in gtfs.items():
    print(name)
    print("Total :",df.count())
    print("Distinct :",df.distinct().count(),"\n")

agency
Total : 70
Distinct : 70

calendar
Total : 277
Distinct : 277

calendar_dates
Total : 24097
Distinct : 24097

feed_info
Total : 1
Distinct : 1

routes
Total : 1669
Distinct : 1669

shapes
Total : 2921218
Distinct : 2921218

stops
Total : 36607
Distinct : 36607

stop_times
Total : 5195977
Distinct : 5195977

trips
Total : 120474
Distinct : 120474

In [13]:
summary = []

for name, df in gtfs.items():

    summary.append((
        name,
        df.count(),
        len(df.columns),
        df.count() - df.distinct().count()
    ))

summary_df = spark.createDataFrame(
    summary,
    ["Dataset","Rows","Columns","Duplicate Rows"]
)

summary_df.show(truncate=False)

+--------------+-------+-------+--------------+
|Dataset       |Rows   |Columns|Duplicate Rows|
+--------------+-------+-------+--------------+
|agency        |70     |7      |0             |
|calendar      |277    |10     |0             |
|calendar_dates|24097  |3      |0             |
|feed_info     |1      |6      |0             |
|routes        |1669   |5      |0             |
|shapes        |2921218|5      |0             |
|stops         |36607  |9      |0             |
|stop_times    |5195977|10     |0             |
|trips         |120474 |9      |0             |
+--------------+-------+-------+--------------+

# Parsing the xml files

Direct pd.read_xml() is not used because the SIRI-VM XML has a deeply nested structure, requiring manual extraction of VehicleActivity records into a tabular format.

In [14]:
import xml.etree.ElementTree as ET
import pandas as pd

tree = ET.parse("Data/Raw/siri.xml")
root = tree.getroot()

ns = {"s": "http://www.siri.org.uk/siri"}

data = []

for v in root.findall(".//s:VehicleActivity", ns):

    j = v.find("s:MonitoredVehicleJourney", ns)
    loc = j.find("s:VehicleLocation", ns)

    data.append([
        v.findtext("s:RecordedAtTime", namespaces=ns),
        j.findtext("s:LineRef", namespaces=ns),
        j.findtext("s:OperatorRef", namespaces=ns),
        j.findtext("s:VehicleRef", namespaces=ns),
        loc.findtext("s:Latitude", namespaces=ns),
        loc.findtext("s:Longitude", namespaces=ns)
    ])

df_siri = pd.DataFrame(data, columns=[
    "RecordedTime",
    "LineRef",
    "Operator",
    "VehicleRef",
    "Latitude",
    "Longitude"
])

df_siri.head()

,RecordedTime,LineRef,Operator,VehicleRef,Latitude,Longitude
0,2026-07-02T15:10:13+00:00,96A,A2BR,3303,51.981412,-0.233722
1,2026-07-02T17:33:39+00:00,16A,A2BR,3311,52.073968,0.008972
2,2026-07-02T18:12:15+00:00,811,A2BV,A2BV-24,53.368135,-3.069226
3,2026-07-02T19:16:10+00:00,1A,A2BV,A2BV-RE24_TDZ,53.365285,-3.065045
4,2026-07-02T17:11:17+00:00,106,A2BV,A2BV-YJ10_MHK,53.419548,-3.046595

In [15]:
df_siri.to_csv("Data/Raw/vehicle.csv", index=False)

In [16]:
# Nested structure of xml file for the distrubtion data

In [17]:
import pandas as pd
df_sirisx = pd.read_xml("Data/Raw/sirisx.xml")
df_sirisx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ResponseTimestamp          1 non-null      object
 1   ProducerRef                1 non-null      object
 2   ResponseMessageIdentifier  1 non-null      object
 3   SituationExchangeDelivery  1 non-null      object
dtypes: object(4)
memory usage: 160.0+ bytes

In [18]:
print(df_sirisx.columns.tolist())

['ResponseTimestamp', 'ProducerRef', 'ResponseMessageIdentifier', 'SituationExchangeDelivery']

In [19]:
display(df_sirisx)

,ResponseTimestamp,ProducerRef,ResponseMessageIdentifier,SituationExchangeDelivery
0,2026-07-03T02:43:42.835Z,DepartmentForTransport,20e2423c-58d1-457a-ab3d-0c3ae171952f,\n

In [20]:
print(df_sirisx.loc[0, "SituationExchangeDelivery"])

In [21]:
import xml.etree.ElementTree as ET

tree = ET.parse("Data/Raw/sirisx.xml")
root = tree.getroot()

for i, elem in enumerate(root.iter()):
    print(elem.tag)
    if i >= 30:
        break

{http://www.siri.org.uk/siri}Siri
{http://www.siri.org.uk/siri}ServiceDelivery
{http://www.siri.org.uk/siri}ResponseTimestamp
{http://www.siri.org.uk/siri}ProducerRef
{http://www.siri.org.uk/siri}ResponseMessageIdentifier
{http://www.siri.org.uk/siri}SituationExchangeDelivery
{http://www.siri.org.uk/siri}ResponseTimestamp
{http://www.siri.org.uk/siri}Situations
{http://www.siri.org.uk/siri}PtSituationElement
{http://www.siri.org.uk/siri}CreationTime
{http://www.siri.org.uk/siri}ParticipantRef
{http://www.siri.org.uk/siri}SituationNumber
{http://www.siri.org.uk/siri}Version
{http://www.siri.org.uk/siri}Source
{http://www.siri.org.uk/siri}SourceType
{http://www.siri.org.uk/siri}TimeOfCommunication
{http://www.siri.org.uk/siri}VersionedAtTime
{http://www.siri.org.uk/siri}Progress
{http://www.siri.org.uk/siri}ValidityPeriod
{http://www.siri.org.uk/siri}StartTime
{http://www.siri.org.uk/siri}PublicationWindow
{http://www.siri.org.uk/siri}StartTime
{http://www.siri.org.uk/siri}MiscellaneousReason
{http://www.siri.org.uk/siri}Planned
{http://www.siri.org.uk/siri}Summary
{http://www.siri.org.uk/siri}Description
{http://www.siri.org.uk/siri}Consequences
{http://www.siri.org.uk/siri}Consequence
{http://www.siri.org.uk/siri}Condition
{http://www.siri.org.uk/siri}Severity
{http://www.siri.org.uk/siri}Affects

In [22]:
df_sirisx = pd.read_xml(
    "Data/Raw/sirisx.xml",
    xpath=".//ns:PtSituationElement",
    namespaces={"ns": "http://www.siri.org.uk/siri"}
)

df_sirisx.head()

,CreationTime,ParticipantRef,SituationNumber,Version,Source,VersionedAtTime,Progress,ValidityPeriod,PublicationWindow,MiscellaneousReason,Planned,Summary,Description,Consequences,InfoLinks,EquipmentReason
0,2024-08-30T09:07:04.813Z,WestofEngland,18224249-29cf-4f65-a023-11067e7c2b6f,5,\n,2025-07-22T07:29:53.362Z,open,\n,\n,roadworks,True,Live Traffic Update: York Road One Way Closure,Long term works - York Road is closed eastboun...,\n,None,None
1,2024-11-01T15:42:15.905Z,WYCA,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,3,\n,2025-02-19T13:24:15.995Z,open,\n,\n,roadworks,True,"Horsforth Vale, Bletchley Avenue, Bletchley Ro...","Bletchley Avenue, Bletchley Road and Low Hall ...",\n,\n,None
2,2025-03-06T09:16:59Z,WestofEngland,ba174836-2698-4f06-8f22-e6c90aca9a7d,1,\n,2025-03-06T09:16:59Z,open,\n,\n,roadworks,False,Tower Road/Station Road,Due to Temporary Lights on the Junction of Tow...,\n,None,None
3,2025-03-28T11:17:43Z,WestofEngland,8e8d2259-4d28-490b-9785-c08b0fd034bd,4,\n,2025-10-15T08:35:49.810Z,open,\n,\n,roadworks,True,"Road Closure: Victoria Street, Bristol","Victoria Street in Bristol City Centre, northb...",\n,None,None
4,2025-03-31T11:39:08Z,WestofEngland,526571b9-9ead-4d5a-a7f0-511c879be31e,1,\n,2025-03-31T11:39:08Z,open,\n,\n,None,True,Stop closure: The Assembly Rooms,This stop will be closed for approximately 20 ...,\n,None,repairWork

In [23]:
df_sirisx.to_csv("Data/Raw/distrubtion.csv", index=False)

In [24]:
def inspect_pandas(name, df):

    print("\n" + "="*90)
    print(f"DATASET : {name}")
    print("="*90)

    print(f"Rows      : {df.shape[0]}")
    print(f"Columns   : {df.shape[1]}")
    print(f"Duplicates: {df.duplicated().sum()}")

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nSummary Statistics")
    display(df.describe(include="all"))

    print("\nSample Records")
    display(df.head())

inspect_pandas("Vehicle", df_siri)
inspect_pandas("Disruptions", df_sirisx)

==========================================================================================
DATASET : Vehicle
==========================================================================================
Rows      : 27502
Columns   : 6
Duplicates: 0

Data Types
RecordedTime    object
LineRef         object
Operator        object
VehicleRef      object
Latitude        object
Longitude       object
dtype: object

Missing Values
RecordedTime     0
LineRef         14
Operator         0
VehicleRef       0
Latitude         0
Longitude        0
dtype: int64

Summary Statistics

,RecordedTime,LineRef,Operator,VehicleRef,Latitude,Longitude
count,27502,27488,27502,27502,27502,27502
unique,18958,2329,365,25622,20989,21230
top,2026-07-03T01:21:09+00:00,1,TFLO,2010,0,0
freq,40,470,7764,6,111,111

Sample Records

,RecordedTime,LineRef,Operator,VehicleRef,Latitude,Longitude
0,2026-07-02T15:10:13+00:00,96A,A2BR,3303,51.981412,-0.233722
1,2026-07-02T17:33:39+00:00,16A,A2BR,3311,52.073968,0.008972
2,2026-07-02T18:12:15+00:00,811,A2BV,A2BV-24,53.368135,-3.069226
3,2026-07-02T19:16:10+00:00,1A,A2BV,A2BV-RE24_TDZ,53.365285,-3.065045
4,2026-07-02T17:11:17+00:00,106,A2BV,A2BV-YJ10_MHK,53.419548,-3.046595

==========================================================================================
DATASET : Disruptions
==========================================================================================
Rows      : 374
Columns   : 16
Duplicates: 0

Data Types
CreationTime           object
ParticipantRef         object
SituationNumber        object
Version                 int64
Source                 object
VersionedAtTime        object
Progress               object
ValidityPeriod         object
PublicationWindow      object
MiscellaneousReason    object
Planned                  bool
Summary                object
Description            object
Consequences           object
InfoLinks              object
EquipmentReason        object
dtype: object

Missing Values
CreationTime             0
ParticipantRef           0
SituationNumber          0
Version                  0
Source                   0
VersionedAtTime          0
Progress                 0
ValidityPeriod           0
PublicationWindow        0
MiscellaneousReason     95
Planned                  0
Summary                  0
Description              0
Consequences             0
InfoLinks              214
EquipmentReason        279
dtype: int64

Summary Statistics

,CreationTime,ParticipantRef,SituationNumber,Version,Source,VersionedAtTime,Progress,ValidityPeriod,PublicationWindow,MiscellaneousReason,Planned,Summary,Description,Consequences,InfoLinks,EquipmentReason
count,374,374,374,374.000000,374,374,374,374,374,279,374,374,374,374,160,95
unique,358,9,374,NaN,1,374,1,1,1,9,2,357,371,1,1,6
top,2025-06-24T09:39:50Z,TfGM,54c6f77a-cfbd-4d80-a516-9346bbd63714,NaN,\n,2026-06-26T07:17:40Z,open,\n,\n,roadworks,True,Victoria - Tram Improvement Works,Due to an emergency road closure on Alan Turin...,\n,\n,maintenanceWork
freq,5,117,1,NaN,374,1,374,374,374,197,298,4,2,374,160,73
mean,NaN,NaN,NaN,3.695187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,10.370257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,110.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Sample Records

,CreationTime,ParticipantRef,SituationNumber,Version,Source,VersionedAtTime,Progress,ValidityPeriod,PublicationWindow,MiscellaneousReason,Planned,Summary,Description,Consequences,InfoLinks,EquipmentReason
0,2024-08-30T09:07:04.813Z,WestofEngland,18224249-29cf-4f65-a023-11067e7c2b6f,5,\n,2025-07-22T07:29:53.362Z,open,\n,\n,roadworks,True,Live Traffic Update: York Road One Way Closure,Long term works - York Road is closed eastboun...,\n,None,None
1,2024-11-01T15:42:15.905Z,WYCA,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,3,\n,2025-02-19T13:24:15.995Z,open,\n,\n,roadworks,True,"Horsforth Vale, Bletchley Avenue, Bletchley Ro...","Bletchley Avenue, Bletchley Road and Low Hall ...",\n,\n,None
2,2025-03-06T09:16:59Z,WestofEngland,ba174836-2698-4f06-8f22-e6c90aca9a7d,1,\n,2025-03-06T09:16:59Z,open,\n,\n,roadworks,False,Tower Road/Station Road,Due to Temporary Lights on the Junction of Tow...,\n,None,None
3,2025-03-28T11:17:43Z,WestofEngland,8e8d2259-4d28-490b-9785-c08b0fd034bd,4,\n,2025-10-15T08:35:49.810Z,open,\n,\n,roadworks,True,"Road Closure: Victoria Street, Bristol","Victoria Street in Bristol City Centre, northb...",\n,None,None
4,2025-03-31T11:39:08Z,WestofEngland,526571b9-9ead-4d5a-a7f0-511c879be31e,1,\n,2025-03-31T11:39:08Z,open,\n,\n,None,True,Stop closure: The Assembly Rooms,This stop will be closed for approximately 20 ...,\n,None,repairWork

# Data Understanding and Relationship

In [25]:
gtfs["routes"].select("route_id").show(5)

gtfs["trips"].select("trip_id","route_id","service_id").show(5)

gtfs["stop_times"].select("trip_id","stop_id","arrival_time","departure_time").show(5)

gtfs["stops"].select("stop_id","stop_name").show(5)

gtfs["calendar"].select("service_id").show(5)

df_siri.head()

df_sirisx.head()

+--------+
|route_id|
+--------+
|       8|
|      30|
|      46|
|      77|
|      92|
+--------+
only showing top 5 rows

+--------------------+--------+----------+
|             trip_id|route_id|service_id|
+--------------------+--------+----------+
|VJ008f72c7264e51c...|       8|        60|
|VJ00b3f1406d79a81...|       8|        60|
|VJ04981b88d9836bc...|       8|        60|
|VJ091fbab84e764cc...|       8|        97|
|VJ1017064c449c957...|       8|        60|
+--------------------+--------+----------+
only showing top 5 rows

+--------------------+------------+------------+--------------+
|             trip_id|     stop_id|arrival_time|departure_time|
+--------------------+------------+------------+--------------+
|VJ00022cf38fdf14a...|9400ZZMAFIR2|    06:59:00|      06:59:00|
|VJ00022cf38fdf14a...|9400ZZMACHO2|    07:01:00|      07:01:00|
|VJ00022cf38fdf14a...|9400ZZMASTW2|    07:02:00|      07:02:00|
|VJ00022cf38fdf14a...|9400ZZMAWIT2|    07:05:00|      07:05:00|
|VJ00022cf38fdf14a...|9400ZZMABNR2|    07:07:00|      07:07:00|
+--------------------+------------+------------+--------------+
only showing top 5 rows

+------------+-------------+
|     stop_id|    stop_name|
+------------+-------------+
|  2500DCL792|     New Line|
|090033104077|     Ness Way|
| 0600MA19191|   Smith Lane|
| 2800S44079B|   Eaton Road|
| 2500IMG2876|Rosehill Road|
+------------+-------------+
only showing top 5 rows

+----------+
|service_id|
+----------+
|         1|
|         3|
|         4|
|        15|
|        16|
+----------+
only showing top 5 rows

,CreationTime,ParticipantRef,SituationNumber,Version,Source,VersionedAtTime,Progress,ValidityPeriod,PublicationWindow,MiscellaneousReason,Planned,Summary,Description,Consequences,InfoLinks,EquipmentReason
0,2024-08-30T09:07:04.813Z,WestofEngland,18224249-29cf-4f65-a023-11067e7c2b6f,5,\n,2025-07-22T07:29:53.362Z,open,\n,\n,roadworks,True,Live Traffic Update: York Road One Way Closure,Long term works - York Road is closed eastboun...,\n,None,None
1,2024-11-01T15:42:15.905Z,WYCA,2b9e1d8f-b0ee-43a7-8ca5-7334d6fc4587,3,\n,2025-02-19T13:24:15.995Z,open,\n,\n,roadworks,True,"Horsforth Vale, Bletchley Avenue, Bletchley Ro...","Bletchley Avenue, Bletchley Road and Low Hall ...",\n,\n,None
2,2025-03-06T09:16:59Z,WestofEngland,ba174836-2698-4f06-8f22-e6c90aca9a7d,1,\n,2025-03-06T09:16:59Z,open,\n,\n,roadworks,False,Tower Road/Station Road,Due to Temporary Lights on the Junction of Tow...,\n,None,None
3,2025-03-28T11:17:43Z,WestofEngland,8e8d2259-4d28-490b-9785-c08b0fd034bd,4,\n,2025-10-15T08:35:49.810Z,open,\n,\n,roadworks,True,"Road Closure: Victoria Street, Bristol","Victoria Street in Bristol City Centre, northb...",\n,None,None
4,2025-03-31T11:39:08Z,WestofEngland,526571b9-9ead-4d5a-a7f0-511c879be31e,1,\n,2025-03-31T11:39:08Z,open,\n,\n,None,True,Stop closure: The Assembly Rooms,This stop will be closed for approximately 20 ...,\n,None,repairWork

In [26]:
gtfs["routes"].select("route_short_name").show(20, False)

+----------------+
|route_short_name|
+----------------+
|4               |
|4S              |
|14              |
|10              |
|11              |
|220             |
|221             |
|643             |
|316             |
|317             |
|127A            |
|288             |
|576             |
|256             |
|314             |
|325             |
|330             |
|346             |
|368             |
|374             |
+----------------+
only showing top 20 rows

In [27]:
df_siri["LineRef"].head(20)

0     96A
1     16A
2     811
3      1A
4     106
5      73
6      81
7      1C
8      91
9      1C
10     82
11     R2
12     R3
13     34
14     14
15     2C
16     12
17     13
18    58L
19     13
Name: LineRef, dtype: object

In [28]:
from pyspark.sql.functions import col, upper, trim

vehicle_spark = spark.createDataFrame(df_siri)
vehicle_with_agency = vehicle_spark.join(
    gtfs["agency"],
    upper(trim(vehicle_spark.Operator)) == upper(trim(gtfs["agency"].agency_noc)),
    "left"
)
matched = vehicle_with_agency.join(
    gtfs["routes"],
    (vehicle_with_agency.agency_id == gtfs["routes"].agency_id) &
    (upper(trim(vehicle_with_agency.LineRef)) == upper(trim(gtfs["routes"].route_short_name))),
    "inner"
)

In [29]:
print(
    round(
        matched.count() / vehicle_spark.count() * 100,
        2
    ),
    "% matched"
)

13.7 % matched

This shows that multiple routes are being mapped to different operators or directions as concluded from the above summary

In [34]:
total = vehicle_spark.count()

# How many vehicles found a matching agency at all?
agency_matched = vehicle_with_agency.filter(col("agency_id").isNotNull()).count()

# Of those, how many also matched a route?
route_matched = matched.count()

print("Total vehicle records:", total)
print("Matched an agency:", agency_matched, f"({round(agency_matched/total*100,1)}%)")
print("Matched agency AND route:", route_matched, f"({round(route_matched/total*100,1)}%)")

Total vehicle records: 27502
Matched an agency: 5379 (19.6%)
Matched agency AND route: 3768 (13.7%)

In [36]:
vehicle_ops = set(row["Operator"] for row in vehicle_spark.select("Operator").distinct().collect())
agency_nocs = set(row["agency_noc"] for row in gtfs["agency"].select("agency_noc").distinct().collect())

overlap = vehicle_ops.intersection(agency_nocs)
print("Distinct operator codes in vehicle data:", len(vehicle_ops))
print("Distinct agency_noc codes in agency table:", len(agency_nocs))
print("Codes that appear in BOTH:", len(overlap))

Distinct operator codes in vehicle data: 365
Distinct agency_noc codes in agency table: 70
Codes that appear in BOTH: 57

In [30]:
gtfs["routes"] \
    .groupBy("route_short_name") \
    .agg(count("*").alias("count")) \
    .filter("count > 1") \
    .orderBy("count", ascending=False) \
    .show(20, False)

+----------------+-----+
|route_short_name|count|
+----------------+-----+
|1               |13   |
|2               |13   |
|7               |9    |
|8               |9    |
|6               |9    |
|3               |8    |
|10              |8    |
|14              |8    |
|15              |7    |
|42              |7    |
|4               |7    |
|52              |6    |
|5               |6    |
|17              |6    |
|60              |6    |
|41              |6    |
|82              |6    |
|9               |6    |
|781             |6    |
|685             |5    |
+----------------+-----+
only showing top 20 rows

In [31]:
gtfs["routes"] \
    .filter("route_short_name = '14'") \
    .show(truncate=False)

+--------+---------+----------------+---------------+----------+
|route_id|agency_id|route_short_name|route_long_name|route_type|
+--------+---------+----------------+---------------+----------+
|46      |OP6      |14              |NULL           |3         |
|4449    |OP132    |14              |NULL           |3         |
|4450    |OP302    |14              |NULL           |3         |
|4456    |OP255    |14              |NULL           |3         |
|43906   |OP258    |14              |NULL           |3         |
|78779   |OP326    |14              |NULL           |3         |
|132122  |OP260    |14              |NULL           |3         |
|132158  |OP260    |14              |NULL           |3         |
+--------+---------+----------------+---------------+----------+

In [32]:
gtfs["agency"].show(truncate=False)

+---------+--------------------------------+--------------------------+---------------+-----------+------------+----------+
|agency_id|agency_name                     |agency_url                |agency_timezone|agency_lang|agency_phone|agency_noc|
+---------+--------------------------------+--------------------------+---------------+-----------+------------+----------+
|OP10     |M & H Coaches                   |https://www.traveline.info|Europe/London  |EN         |NULL        |MHCO      |
|OP1092   |Mersey Ferries                  |https://www.traveline.info|Europe/London  |EN         |NULL        |FRRY      |
|OP10924  |Bee Network                     |https://www.traveline.info|Europe/London  |EN         |NULL        |BNSM      |
|OP11023  |Bee Network                     |https://www.traveline.info|Europe/London  |EN         |NULL        |BNDB      |
|OP11056  |Bee Network                     |https://www.traveline.info|Europe/London  |EN         |NULL        |BNVB      |
|OP11122  |Bee Network                     |https://www.traveline.info|Europe/London  |EN         |NULL        |BNGN      |
|OP11952  |Duck Tours                      |https://www.traveline.info|Europe/London  |EN         |NULL        |DUCK      |
|OP12376  |Bee Network                     |https://www.traveline.info|Europe/London  |EN         |NULL        |BNFM      |
|OP132    |High Peak                       |https://www.traveline.info|Europe/London  |EN         |NULL        |HIPK      |
|OP13829  |Bee Network                     |https://www.traveline.info|Europe/London  |EN         |NULL        |BNML      |
|OP1389   |Belle Vue Coaches               |https://www.traveline.info|Europe/London  |EN         |NULL        |BEVC      |
|OP14131  |A and J Taxis                   |https://www.traveline.info|Europe/London  |EN         |NULL        |AJTX      |
|OP14137  |Iain McGregor                   |https://www.traveline.info|Europe/London  |EN         |NULL        |IMAC      |
|OP14144  |Mountain Goat Holidays and Tours|https://www.traveline.info|Europe/London  |EN         |NULL        |MTGT      |
|OP212    |Borders Buses                   |https://www.traveline.info|Europe/London  |EN         |NULL        |BORD      |
|OP213    |Go North East                   |https://www.traveline.info|Europe/London  |EN         |NULL        |GNEL      |
|OP220    |Stagecoach North East           |https://www.traveline.info|Europe/London  |EN         |NULL        |SCNE      |
|OP222    |Telford's Coaches               |https://www.traveline.info|Europe/London  |EN         |NULL        |TELF      |
|OP225    |Wright Brothers Coaches         |https://www.traveline.info|Europe/London  |EN         |NULL        |WGTB      |
|OP229    |Arriva North East               |https://www.traveline.info|Europe/London  |EN         |NULL        |ANEA      |
+---------+--------------------------------+--------------------------+---------------+-----------+------------+----------+
only showing top 20 rows

In [33]:
gtfs["routes"].show(10, truncate=False)

+--------+---------+----------------+---------------+----------+
|route_id|agency_id|route_short_name|route_long_name|route_type|
+--------+---------+----------------+---------------+----------+
|8       |OP6      |4               |NULL           |3         |
|30      |OP6      |4S              |NULL           |3         |
|46      |OP6      |14              |NULL           |3         |
|77      |OP6      |10              |NULL           |3         |
|92      |OP6      |11              |NULL           |3         |
|753     |OP13829  |220             |NULL           |3         |
|754     |OP13829  |221             |NULL           |3         |
|950     |OP326    |643             |NULL           |3         |
|1511    |OP31     |316             |NULL           |3         |
|1512    |OP31     |317             |NULL           |3         |
+--------+---------+----------------+---------------+----------+
only showing top 10 rows